[mysql.master]
type = 'mysql'
host = 'localhost'
port = '3406'
user = 'root'
password = 'root'
name = 'next0'
tablepre = 'bbs_'
charset = 'utf8'
engine = 'innodb'

[[mysql.slave]]


[[cache]]
host = 'localhost'
port = '11211'
cachepre = 'bbs_'
cachetype = 'memcached'

[[cache]]
host = 'localhost'
port = '11211'
cachepre = 'bbs_'
cachetype = 'redis'

[site_config]
tmp_path = './tmp/'		# 可以配置为 linux 下的 /dev/shm ，通过内存缓存临时文件
log_path = './log/'		# 日志目录

# -------------------> xiuno bbs 4.0 配置
tmpl_path = './view/htm/*.tmpl'
view_url = '/unmoved/'		# 可以配置单独的 CDN 域名：比如：http:#static.domain.com/unmoved/
view_path = './static/'	    # 物理路径
upload_url = './upload/'	# 可以配置单独的 CDN 域名：比如：http:#upload.domain.com/upload/
upload_path = './upload/'	# 物理路径，可以用 NFS 存入到单独的文件服务器

logo_mobile_url = '/unmoved/img/logo.png'		# 手机的 LOGO URL
logo_pc_url = '/unmoved/img/logo.png'			# PC 的 LOGO URL
logo_water_url = '/unmoved/img/water-small.png'		# 水印的 LOGO URL

sitename = 'Xiuno BBS'
sitebrief = 'Site Brief'
timezone = 'Asia/Shanghai'	# 时区，默认中国
lang = 'zh-cn'
runlevel = 5		# 0: 站点关闭; 1: 管理员可读写; 2: 会员可读;  3: 会员可读写; 4：所有人只读; 5: 所有人可读写
runlevel_reason = 'The site is under maintenance please visit later.'

keywords ='some keywords'
description ='some description'
title = 'site title'
mobile_link = './mobile/'
mobile_title = 'mobile title'
base_href = 'base_href/aaa/bbb'

cookie_domain = ''
cookie_path = ''
auth_key = 'efdkjfjiiiwurjdmclsldow753jsdj438'

pagesize = 20
postlist_pagesize = 100
cache_thread_list_pages = 10
online_update_span = 120	# 在线更新频度，大站设置的长一些
online_hold_time = 3600	# 在线的时间
session_delay_update = 0
upload_image_width = 927	# 上传图片自动缩略的最大宽度
order_default = 'lastpid'
attach_dir_save_rule = 'Ym'	# 附件存放规则，附件多用：Ymd，附件少：Ym

update_views_on = 1
user_create_email_on = 0
user_create_on = 1
user_resetpw_on = 0

admin_bind_ip = 0		# 后台是否绑定 IP

cdn_on = 0

# 支持多种 URL 格式：
#	0: ?thread-create-1.htm
#	1: thread-create-1.htm
#	2: ?/thread/create/1  不支持
#	3: /thread/create/1   不支持
url_rewrite_on = 0

# 禁止插件
disabled_plugin = 0

version = '4.0.4'
static_version = '?1.0'
installed = 0

[attach_config]
all = ['av','wmv','wav','wma','avi','rm','rmvb','mp4', 'mp3','exe','bin','swf','fla','as','gif','jpg','jpeg','png','bmp','doc','xls','ppt','docx','xlsx','pptx','pdf',
		'c','cpp','cc', 'txt','tar','zip','gz','rar','7z','bz','chm','bt','torrent','ttf','font','fon']
video = ['av','wmv','wav','wma','avi','rm','rmvb','mp4']
music = ['mp3','mp4']
exe = ['exe','bin']
flash = ['swf','fla','as']
image = ['gif','jpg','jpeg','png','bmp']
office = ['doc','xls','ppt','docx','xlsx','pptx']
pdf = ['pdf']
text = ['c','cpp','cc', 'txt']
zip = ['tar','zip','gz','rar','7z','bz']
book = ['chm']
torrent = ['bt','torrent']
font = ['ttf','font','fon']
other = []